// Generated by https://quicktype.io

export interface DataForPDF {
    control_date:             string;
    total_offers_managed:     number;
    total_cotizations:        number;
    offers_managed_companies: OffersManagedCompany[];
}

export interface OffersManagedCompany {
    company_name:          string;
    sum_cotizations:       number;
    total_offers:          number;
    percentage:            string;
    percentage_cotization: string;
}
